### ISSUE TITLE
Container build fails locally

### ISSUE THREAD

**Issue by cjchirag7** [camicroscope/Distro#107]
**Describe the bug**
When building the application with ```docker-compose -f caMicroscope.yml up```, it fails with the below error :
```
Building iip
ERROR: error fetching: fatal: unable to find remote helper for 'https'
: exit status 128
```
I am using docker-compose version 1.25.4 build unkown, Docker version 18.09.9, build 1752eb3. 

**To Reproduce**
1. Clone this [repository](https://github.com/camicroscope/Distro)
2. Inside the repository folder, open your terminal
3. Run ```docker-compose -f caMicroscope.yml up``` (using sudo privilidges)

**Expected behavior**
The application should run at http://localhost:4010

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Comment by viditvarshney** [comment]
there had a discussion about this in the slack groupas well,
 are you joined the slack group?

**Comment by birm** [comment]
Can we get the git version too?

**Comment by cjchirag7** [comment]
@birm , My git version is 2.26.0 . I tried the solutions given here :  https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone, but none worked for me.

**Comment by cjchirag7** [comment]
@viditvarshney  thanks, I had already joined the slack group and followed the discussion there too but it didn't help.

**Comment by AlinaBoshchenko** [comment]
Hey @cjchirag7 have you tried running _**docker-compose -f caMicroscope.yml up**_ without sudo?
It should help as docker should be in the same user group as you are, thus not require sudo in order to run it properly.

**Comment by cjchirag7** [comment]
Yes, @AlinaBoshchenko , yes I tried that. But the errors as commented [here](https://github.com/camicroscope/Distro/issues/98#issuecomment-596052533), by zengchu2 came up.

**Comment by cjchirag7** [comment]
Then, I followed @birm on slack, where he told to change 
```    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json 
```
to
```    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/:/root/bindaas/bin/
```
As a result, this error also went away. But I faced the below error :

```
ca-data     | WARNING: no logs are available with the 'none' log driver
ca-data exited with code 2
ca-security | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
ca-security | fs.js:675
ca-security |   return binding.read(fd, buffer, offset, length, position);
ca-security |                  ^
ca-security | 
ca-security | Error: EISDIR: illegal operation on a directory, read
ca-security |     at Object.fs.readSync (fs.js:675:18)
ca-security |     at tryReadSync (fs.js:540:20)
ca-security |     at Object.fs.readFileSync (fs.js:583:19)
ca-security |     at Object.<anonymous> (/root/src/router.js:67:36)
ca-security |     at Module._compile (module.js:653:30)
ca-security |     at Object.Module._extensions..js (module.js:664:10)
ca-security |     at Module.load (module.js:566:32)
ca-security |     at tryModuleLoad (module.js:506:12)
ca-security |     at Function.Module._load (module.js:498:3)
ca-security |     at Function.Module.runMain (module.js:694:10)
ca-security |     at startup (bootstrap_node.js:204:16)
ca-security |     at bootstrap_node.js:625:3
ca-security | error: Forever detected script exited with code: 1
ca-security | error: Script restart attempt #1
....
```

**Comment by mgautam98** [comment]
Check if you have multiple instances of docker-compose. Purge all the docker-compose installation and have a fresh one.

**Comment by cjchirag7** [comment]
@mgautam98 , thanks. I read discussion at this link earlier also and tried uninstalling docker and docker-compose and reinstalling them. It didn't work, maybe as I was not able to uninstall docker completely.

But this time, I tried doing it once again, after uninstalling docker and docker-compose from my system completely , following https://stackoverflow.com/questions/30988566/how-do-i-uninstall-docker-compose .
And reinstalled it again  and it worked !!

**Comment by mgautam98** [comment]
@cjchirag7 I am happy that it worked.
