### ISSUE TITLE
Saving for Draw tool is not working properly

### ISSUE THREAD

**Issue by AlinaBoshchenko** [camicroscope/Distro#109]
**To Reproduce**
1. Select Draw tool
2. Type name
3. Select area on the picture
4. Type note
5. No **Save** button

**Expected behavior**
Either area should be automatically saved or Save button should appear 

**Screenshots**
![image](https://user-images.githubusercontent.com/42976128/78045793-0929da00-737f-11ea-9666-1211274b5c90.png)

**Note**
Everything is working as expected if you firstly type name and note and select area only after that.

**Comment by mgautam98** [comment]
The save button will appear by clicking on the drawing tool icon. 
The first time you open it opens the Annotation form the second time you click it shows "save" button.

**Comment by cjchirag7** [comment]
@mgautam98, @birm   but still when you try clicking on 'save' button with an **empty note**, it doesn't save. 

And when you check the console, you find the following errors -
```
draw-overlay:stop-drawing error:
stopDrawing @ openseadragon-canvas-draw-overlay.js:653
openseadragon-canvas-draw-overlay.js:654 TypeError: Cannot read property 'length' of undefined
    at anno_callback (uicallbacks.js:1115)
    at saveAnnotation (uicallbacks.js:1594)
    at Object.stopDrawing [as handler] (uicallbacks.js:1642)
    at eventsource.js:162
    at $.CanvasDraw.raiseEvent (eventsource.js:184)
    at $.CanvasDraw.stopDrawing (openseadragon-canvas-draw-overlay.js:650)
stopDrawing @ openseadragon-canvas-draw-overlay.js:654
uicallbacks.js:1115 Uncaught TypeError: Cannot read property 'length' of undefined
    at anno_callback (uicallbacks.js:1115)
    at OperationPanel.<anonymous> (operationpanel.js:202)
```

I have fixed this bug, with [PR-298](https://github.com/camicroscope/caMicroscope/pull/298) of caMicroscope repository.

**Comment by cjchirag7** [comment]
Now, it is automatically saving:
![create-annotation-empty](https://user-images.githubusercontent.com/45796806/78241447-ff7ab080-74fd-11ea-8425-dce3f728035f.gif)
