### ISSUE TITLE
Draw tool UI issue - can't select color for the area

### ISSUE THREAD

**Issue by AlinaBoshchenko** [camicroscope/Distro#110]
**To Reproduce**
1. Click on the Draw tool icon
2. Form for the name and note typing appears

Just for a moment before form for the name and note typing appears you can see the drop-down menu for color selection. It could not be accessed because it is immediately overlapped by the form.

**Expected behavior**
Ability to access the drop-down menu and select color for the area.

**Screenshots**
![image](https://user-images.githubusercontent.com/42976128/78047352-ea2c4780-7380-11ea-971d-fd9a81092c24.png)

**Comment by mgautam98** [comment]
You can change the color of the tool color from the Annotation sub tool menu, which you can acces by right clicking anywhere on the image. Thanks for the issue. This shows we need nice manual for the users.
![Screenshot from 2020-04-01 14-22-08](https://user-images.githubusercontent.com/29784549/78118324-7e031f80-7424-11ea-98a3-aee320275743.png)

**Comment by cjchirag7** [comment]
We can add a popup message, to be displayed to user for a small time, showing him that for more options, he needs to right click anywhere on the image.

**Comment by birm** [comment]
@AlinaBoshchenko does #299 resolve your issue?
