### ISSUE TITLE
index container permission issue on windows + ubuntu SSH

### ISSUE THREAD

**Issue by 3048205169** [camicroscope/Distro#127]
**Describe the bug**
In Nanoborb, after open the .svs file, there will be a toolbar on the left-top on the website, and there is a "draw" on the toolbar.

In nanoborb, this tool can be successfully used to draw lines but in the server of caMicroscope (after hosted setup) will show errors: for more options, balabala... and then nothing will change no lines can be drawn.

**To Reproduce**
1. Do the hosted setup in Linux (mine is Ubuntu)
2. Input command: "docker-compose -f development.yml up" under the directory: Distro
3. Open the website: _the ip address + 4010_ and then get into the website 
4. Then upload a .svs file onto the server
5. Open this file on server
6. Use the draw tool in the toolbox
6. See error
    My browser is google chrome which has an error: 
    Uncaught TypeError: Cannot read property 'style' of undefined
      at MouseEvent.annotationOn (uicallbacks.js:411)
      at MouseEvent.<anonymous> (uicallbacks.js:295)

**Expected behavior**
I hope the draw tool in server just appears the same function like Nanoborb

**Screenshots**
![error](https://user-images.githubusercontent.com/38618523/84871762-837f1600-b0b3-11ea-9561-758f449036ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, SSH with Ubuntu 
 - Browser google chrome version 83.0.4103.97

**Additional context**
In Windows Edge, it even cannot open the website! thus I wonder if it is the error with Browser!

**Comment by birm** [comment]
Thanks for the bug report! I think I know what's causing this issue, so I hope you don't mind if I ask you to check something in the database.
Can you check mongo via `docker exec -ti ca-mongo mongo` and see if you notice anything in the camic db, template collection?

**Comment by 3048205169** [comment]
This is the screenshot after running `docker exec -ti ca-mongo mongo`
![mongo](https://user-images.githubusercontent.com/38618523/84966059-16b35c80-b143-11ea-83e1-79af9e263bbd.png)

**Comment by birm** [comment]
yes, from this prompt, run `use camic` then `db.template.find().pretty()`

**Comment by 3048205169** [comment]
![camic](https://user-images.githubusercontent.com/38618523/84966197-7a3d8a00-b143-11ea-87cb-b01054efe437.png)

**Comment by birm** [comment]
Don't forget the () at the end of pretty.

**Comment by 3048205169** [comment]
Sorry! 
![camic](https://user-images.githubusercontent.com/38618523/84966293-c7216080-b143-11ea-8dde-02e9ac82f245.png)

**Comment by birm** [comment]
Thanks!
There are no templates in the db, so, it's clear that this step (https://github.com/camicroscope/Distro/blob/master/config/default_data.js) has been skipped somehow.
Sorry to bug you more, but can you remove lines 7, 8, 14, and 15 from develop.yml (both sets are logging: driver none) and see if ca-mongo or ca-idx say anything interesting on startup?

**Comment by 3048205169** [comment]
OK, I will exactly do that!

**Comment by 3048205169** [comment]
![txt](https://user-images.githubusercontent.com/38618523/84966641-942b9c80-b144-11ea-9bba-6f3ff73e3eae.png)

**Comment by 3048205169** [comment]
![update1](https://user-images.githubusercontent.com/38618523/84966816-04d2b900-b145-11ea-82a8-8e93d67d66af.png)
![update2](https://user-images.githubusercontent.com/38618523/84966821-07cda980-b145-11ea-9203-d9816a21d19a.png)

**Comment by birm** [comment]
Ah, a permission error on run_idx.sh! You implied this is windows, but could you (from your host machine, Distro folder) run `ls -alt config/run_idx.sh` to see if it has execution permissions?

**Comment by 3048205169** [comment]
-rw-rw-r-- 1 (the user name of Ubuntu and the date and time) config/run_idx.sh

**Comment by birm** [comment]
Okay, can you see if the change in  https://github.com/camicroscope/Distro/commit/390f78426a750c90cc915f59be7aaa1a28016d2d resolves your issue?

**Comment by 3048205169** [comment]
YEs! the drawing function now can be used! Thanks a lot!

> Okay, can you see if the change in  390f784 resolves your issue?

**Comment by 3048205169** [comment]
But another little drawback is shown in google chrome: A Self-Intersecting Polygon Will Cause Inaccurate Area and Circumference. DOes it matter?

**Comment by birm** [comment]
We use the shoelace algorithm for calculating the area for polygons, but it fails in the intersecting case. It's just a warning that the area number given will be wrong. :)

**Comment by 3048205169** [comment]
> We use the shoelace algorithm for calculating the area for polygons, but it fails in the intersecting case. It's just a warning that the area number given will be wrong. :)

It makes sense. I will do my rest function testing on this software!

**Comment by birm** [comment]
Thanks for your patience and cooperation in helping us with this. I'm still not sure exactly _why_ this permission issue has happened, but starting next release, we should sidestep that entirely. :confetti_ball:
