### ISSUE TITLE
Some questions about the inner mechanism of saving annotations

### ISSUE THREAD

**Issue by 3048205169** [camicroscope/Distro#132]
After observation, I guess, this entire software uses js to make not only the front end but also the back end?

The question is, If I choose the preset label tool in the tool bar and choose the Tumor, Positive, 2000. Then I draw and drag on the slide, then annotation will be saved in the mongoDB. AND, what functions will be called in this process? Which files will be used?

**Comment by nanli-emory** [comment]
Hi @3048205169. I'm sorry for responding so late. Thanks for your patience and understanding.
Yes, you are right. In QUIP stack, we use js to make both front-end and back-end.
Actually, there are two docker containers. 

[CaMicroscope](https://github.com/camicroscope/caMicroscope) is a front-end provider. 
[Caracal](https://github.com/camicroscope/Caracal) is a back-end provider.

At Front-end, you should check on [apps/viewer/uicallbacks.js](https://github.com/camicroscope/caMicroscope/blob/develop/apps/viewer/uicallbacks.js). At this file, we call **$CAMIC.store.addMark** to save annotations.

The [core/Store.js](https://github.com/camicroscope/caMicroscope/blob/develop/core/Store.js) is a storage interpreter for camicroscope. We can use Store.js to provide different storage service such as store data into backend/ BD or local storage (see  [Nanoborb](https://github.com/camicroscope/Nanoborb)).

At Back-End, [handlers/dataHandlers.js](https://github.com/camicroscope/Caracal/blob/master/handlers/dataHandlers.js).

Also, we are working on an architecture diagram for QUIP. We will let you know if it updates on site. Thanks. :)

**Comment by birm** [comment]
Closed as stale. Please feel free to reopen this or open a new issue if needed.
