### ISSUE TITLE
Running without an identity provider

### ISSUE THREAD

**Issue by jfkotw** [camicroscope/Distro#142]
Is it possible to run the software without requiring an identity provider?

If not are there any instructions for running with e.g. a keycloak container to allow setting up a simple test environment without needing a google account?

**Comment by birm** [comment]
Have you tried the config in develop.yml?
The following environment variables should make use of an identity provider optional. https://github.com/camicroscope/Distro/blob/42eb9251089ee8e5ef64bc2ff7d1cf88c8b5548a/develop.yml#L39

We're _slowly_ working on an auth container or equivalent similar to what you've proposed, but anything which has the required fields in a jwt with an appropriate signature, matching "JWK_URL"

**Comment by jfkotw** [comment]
Thanks for the tip, solved the issue for me. Looking forward to the developments, and happy to test anything once it is ready.
