### ISSUE TITLE
Uploading slides not working

### ISSUE THREAD

**Issue by jfkotw** [camicroscope/Distro#144]
**Describe the bug**
I've been trying to get caMicroscope running on my local docker-compose setup and have run into an issue when attempting to upload images to get started with testing.

I downloaded an example ndpi file from the openslide website: 
http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/CMU-1.ndpi
This slide opens fine in Nanoborb and also 

**To Reproduce**
1. Launch caMicroscope using the unmodified develop.yml from the Distro repo.
2. Download: http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/CMU-1.ndpi
3. Upload CMU-1.ndpi from your local PC.
4. Wait until upload is complete.
5. Click Finish Upload
6. Click Check
At that point there is an error thrown in the browser console:
loader.js:69 Uncaught (in promise) TypeError: Cannot set property 'innerHTML' of undefined
    at loader.js:69
7. No file appears in the list of slides page.

**Expected behavior**
Should be able to upload slides :-D
Actually the bulk upload option with the single slide does work.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85

**Comment by birm** [comment]
Actually, I'm having a hard time replicating this. Can you confirm if it's still an issue?

**Comment by jfkotw** [comment]
I just ran git pull on https://github.com/camicroscope/Distro/
Then ran:
docker-compose -f develop.yml build --force-rm
and
docker-compose -f develop.yml up --force-recreate

The issue remains for me. One more thing that may be relevant. The docker containers are running on my desktop, and I'm accessing the website from my laptop.

**Comment by birm** [comment]
Tricky bug. To be honest, I'm not sure what about the ndpi file caused it, but it should be resolved in 3.8.1 (or current develop)

**Comment by birm** [comment]
If you can, please try rebuilding the services, or at least the ca-back container, and see if that resolves your issues.

**Comment by jfkotw** [comment]
Confirmed that it works for me now. Thanks!

**Comment by birm** [comment]
Thanks for reporting this and working with us!
