### ISSUE TITLE
Kubernetes Config

### ISSUE THREAD

**Issue by birm** [camicroscope/Distro#183]
We need a working and easy kubernetes config. Kompose alone has been insufficient so far.

**Comment by RAMESSESII2** [comment]
Hey @birm, please assign this issue to me. 
Also if I may know, why do you want to move from auto-generated k8s-config of Kompose to custom-written yamls?

**Comment by birm** [comment]
The primary thing that we actually needed to do was to add secrets and configmaps. Me doing the whole thing manually was likely unnecessary. 
I will accept pull requests against https://github.com/camicroscope/Distro/tree/develop/kubernetes if you'd like to change something.
