### ISSUE TITLE
A service can not depend on itself

### ISSUE THREAD

**Issue by swvanderlaan** [camicroscope/Distro#193]
**Describe the bug**
After creating a directory to clone `caMicroscope` into, I received this error:

> ERROR: A service can not depend on itself: mongo

**To Reproduce**
These were the steps I took:

```
cd $HOME
mkdir -v camicroscope
cd camicroscope
git clone git@github.com:camicroscope/Distro.git
docker-compose -f caMicroscope.yml up
```

**Expected behavior**
I am expecting a smooth start of the installation. A quick solution is to change the following in the `caMicroscope.yml`-file:

```
# this part of the code is wrong - 'ERROR: A service can not depend on itself: mongo'
#    depends_on:
#      - mongo
```

One can't reference a service to itself.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS Monterey, v12.5 
 - `home-brew`: 

```
brew config
HOMEBREW_VERSION: 3.5.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: ce8ef89ec0cfe875c48c3a83a843af9074c05930
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2745e4f9b1473f148ce8d8e9aeb779f204c25541
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.EQK4w2iKJT/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
```

**Smartphone (please complete the following information):**
n/r

**Additional context**
none

**Comment by birm** [comment]
Thank you for reporting. I've updated that file, does that solve your
problem?
