### ISSUE TITLE
Installation of distro with docker compose fails

### ISSUE THREAD

**Issue by catweis** [camicroscope/Distro#203]
**Describe the bug**
I tried to install the Distro-version from GitHub with docker compose. But it exists with some error code, I do not understand.
For testing, I have used a clean and new linux system, twice. 

**To Reproduce**
1. I have downloaded the Distro from GitHub
2. I started the installation with docker-compose -f dh_caMicroscope.yml up
3. There is the following error:

Creating network "distro_default" with the default driver
Pulling mongo (mongo:4.2-bionic)...
4.2-bionic: Pulling from library/mongo
456d651ccb27: Pull complete
0d873b46166f: Pull complete
b700537f311e: Pull complete
8ba0f53e4854: Pull complete
80b58c92c83f: Pull complete
f4ed2f74d01b: Pull complete
0a2bd86063a1: Pull complete
9d3479b42a1a: Pull complete
59e7441cc47f: Pull complete
Digest: sha256:b9633e6eb4ff0b96ab48a14e0b3792bb185a5daa3ea4c83b69e0bec2a8f5379a
Status: Downloaded newer image for mongo:4.2-bionic
Pulling back (camicroscope/caracal:latest)...
latest: Pulling from camicroscope/caracal
fa1690ae9228: Pull complete
2e799f213a71: Pull complete
83086ca62414: Pull complete
83fd155f6c91: Pull complete
71f84117b593: Pull complete
3b0d74d5e595: Pull complete
2663b58c5f3c: Pull complete
cfd4e70f8767: Pull complete
f1649ad9b855: Pull complete
a6f29a811e51: Pull complete
dbf6e08966fb: Pull complete
Digest: sha256:d32d2ad6e51e3069a706c8112f1d03d2d7aa0431c4db1dd4a2a3ded59f303b5f
Status: Downloaded newer image for camicroscope/caracal:latest
Pulling iip (camicroscope/iipimage:latest)...
latest: Pulling from camicroscope/iipimage
d519e2592276: Pulling fs layer
d22d2dfcfa9c: Pulling fs layer
b3afe92c540b: Pulling fs layer
f132eb32600c: Pulling fs layer
656eed345341: Pulling fs layer
d997a5b00862: Pulling fs layer
ce1a16d57185: Pulling fs layer
e9dccd3e9305: Pulling fs layer
aa944791aaff: Pulling fs layer
cbda0eed89e4: Pulling fs layer
f3ac8c6696a1: Pull complete
6d5c0609bf72: Pull complete
7f3f4e19709b: Pull complete
ad5706679bdd: Pull complete
29cab59db9cd: Pull complete
1b62486b3399: Pull complete
0e1c109062c2: Pull complete
be6e5f2ea5d3: Pull complete
d1c79b973fac: Pull complete
7af66d892f09: Pull complete
914f9ce178a0: Pull complete
8f2e3273d3d0: Pull complete
35ee6dcf95b0: Pull complete
ffe2fd0e000f: Pull complete
94b64151fccc: Pull complete
7efeff70c246: Pull complete
d976816aa311: Pull complete
72fd4d475a96: Pull complete
51b3ffa03cab: Pull complete
1014c1f41d2c: Pull complete
ba761b93afcc: Pull complete
d9454aad60f1: Pull complete
2d9dbc6fd99e: Pull complete
8e9a76dca507: Pull complete
3c4055694229: Pull complete
2f2c1aefbd04: Pull complete
ae8b2a79ed36: Pull complete
4fd8460f80d9: Pull complete
e537ba43b279: Pull complete
Digest: sha256:0d4bdc55e5fd77f992ab1d1bb44c570b9d587255a3ca955c050caad37dcc979c
Status: Downloaded newer image for camicroscope/iipimage:latest
Pulling loader (camicroscope/slideloader:latest)...
latest: Pulling from camicroscope/slideloader
092586df9206: Pull complete
ef599477fae0: Pull complete
4530c6472b5d: Pull complete
d34d61487075: Pull complete
87fc2710b63f: Pull complete
f142141aaad3: Pull complete
12eb19f5f2be: Pull complete
d34466b69a2a: Pull complete
fd8a0746ef83: Pull complete
b9b92267804c: Pull complete
1bb86f6ffd2d: Pull complete
513a8c6698db: Pull complete
307b5b83655c: Pull complete
ef7f501267da: Pull complete
63f5bed8872f: Pull complete
85e39ac47182: Pull complete
bee7e3f8cb13: Pull complete
1739564bb1c5: Pull complete
ce80f8bd8fa7: Pull complete
07501b932e7b: Pull complete
8f2046c0eea2: Pull complete
8c0e32917d16: Pull complete
aa0a77d81757: Pull complete
Digest: sha256:0b42150b5be5b4d070c6eeade5c58db98a4e677f1376c03704f39b4b72b98b4e
Status: Downloaded newer image for camicroscope/slideloader:latest
Creating ca-load  ... done
Creating ca-iip   ... done
Creating ca-mongo ... done
Creating ca-back  ... done
Creating ca-idx   ... done
Attaching to ca-iip, ca-mongo, ca-load, ca-back, ca-idx
ca-idx      | /usr/local/bin/docker-entrypoint.sh: line 418: /config/run_idx.sh: No such file or directory
ca-load     | [2023-02-19 11:49:49 +0000] [7] [INFO] Starting gunicorn 20.0.4
ca-load     | [2023-02-19 11:49:49 +0000] [7] [INFO] Listening at: http://0.0.0.0:4000 (7)
ca-load     | [2023-02-19 11:49:49 +0000] [7] [INFO] Using worker: sync
ca-load     | [2023-02-19 11:49:49 +0000] [10] [INFO] Booting worker with pid: 10
ca-load     | [2023-02-19 11:49:49 +0000] [11] [INFO] Booting worker with pid: 11
ca-load     | [2023-02-19 11:49:49 +0000] [12] [INFO] Booting worker with pid: 12
ca-load     | [2023-02-19 11:49:49 +0000] [13] [INFO] Booting worker with pid: 13
ca-mongo    | 2023-02-19T11:49:48.860+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
ca-mongo    | 2023-02-19T11:49:48.864+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=1db79c011754
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] db version v4.2.23
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] git version: f4e6602d3a4c5b22e9d8bcf0722d0afd0ec01ea2
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] modules: none
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] build environment:
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten]     distarch: x86_64
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
ca-mongo    | 2023-02-19T11:49:48.864+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
ca-mongo    | 2023-02-19T11:49:48.865+0000 I  STORAGE  [initandlisten] 
ca-mongo    | 2023-02-19T11:49:48.865+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
ca-mongo    | 2023-02-19T11:49:48.865+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
ca-mongo    | 2023-02-19T11:49:48.866+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3468M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
ca-mongo    | 2023-02-19T11:49:49.896+0000 I  STORAGE  [initandlisten] WiredTiger message [1676807389:896650][1:0x7f147a9cbb00], txn-recover: Set global recovery timestamp: (0, 0)
ca-mongo    | 2023-02-19T11:49:49.941+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
ca-mongo    | 2023-02-19T11:49:50.082+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
ca-mongo    | 2023-02-19T11:49:50.189+0000 I  CONTROL  [initandlisten] 
ca-mongo    | 2023-02-19T11:49:50.189+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
ca-mongo    | 2023-02-19T11:49:50.189+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
ca-mongo    | 2023-02-19T11:49:50.189+0000 I  CONTROL  [initandlisten] 
ca-mongo    | 2023-02-19T11:49:50.196+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 06888b0d-15ff-4337-8a61-ee26f8b4dd0b and options: { uuid: UUID("06888b0d-15ff-4337-8a61-ee26f8b4dd0b") }
ca-mongo    | 2023-02-19T11:49:50.263+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
ca-mongo    | 2023-02-19T11:49:50.263+0000 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
ca-mongo    | 2023-02-19T11:49:50.264+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
ca-mongo    | 2023-02-19T11:49:50.264+0000 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 48415917-8462-4661-8518-fa1699db7289 and options: { capped: true, size: 10485760 }
ca-mongo    | 2023-02-19T11:49:50.333+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
ca-mongo    | 2023-02-19T11:49:50.334+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
ca-mongo    | 2023-02-19T11:49:50.337+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
ca-mongo    | 2023-02-19T11:49:50.337+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
ca-mongo    | 2023-02-19T11:49:50.337+0000 I  NETWORK  [listener] Listening on 0.0.0.0
ca-mongo    | 2023-02-19T11:49:50.337+0000 I  NETWORK  [listener] waiting for connections on port 27017
ca-mongo    | 2023-02-19T11:49:50.337+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: 26709a37-d3d4-4eb4-9418-7175e9465f0a and options: { uuid: UUID("26709a37-d3d4-4eb4-9418-7175e9465f0a") }
ca-mongo    | 2023-02-19T11:49:50.510+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
ca-mongo    | 2023-02-19T11:49:50.608+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
ca-mongo    | 2023-02-19T11:49:50.608+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 200 megabytes of RAM
ca-mongo    | 2023-02-19T11:49:50.608+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
ca-mongo    | 2023-02-19T11:49:50.609+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
ca-mongo    | 2023-02-19T11:49:50.625+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
ca-mongo    | 2023-02-19T11:49:50.631+0000 I  COMMAND  [LogicalSessionCacheRefresh] command config.system.sessions command: createIndexes { createIndexes: "system.sessions", indexes: [ { key: { lastUse: 1 }, name: "lsidTTLIndex", expireAfterSeconds: 1800 } ], $db: "config" } numYields:0 reslen:114 locks:{ ParallelBatchWriterMode: { acquireCount: { r: 2 } }, ReplicationStateTransition: { acquireCount: { w: 3 } }, Global: { acquireCount: { r: 1, w: 2 } }, Database: { acquireCount: { r: 1, w: 2, W: 1 } }, Collection: { acquireCount: { r: 4, w: 1, R: 1, W: 2 } }, Mutex: { acquireCount: { r: 3 } } } flowControl:{ acquireCount: 1, timeAcquiringMicros: 1 } storage:{} protocol:op_msg 293ms
ca-back     | prikey does not exist
ca-back     | pubkey does not exist
ca-idx exited with code 127
ca-back     | 2023-02-19 11:49:51.333783: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
ca-back     | 2023-02-19 11:49:51.355351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
ca-back     | 2023-02-19 11:49:51.355829: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5b9fe80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
ca-back     | 2023-02-19 11:49:51.355891: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
ca-back     | handler named "updateMarksLabel" not found (rule 23 handler 0)
ca-back exited with code 1

**Comment by catweis** [comment]
Meanwhile, I found the error. The Linux system I used was not "strong" enough for mongo. By testing a single mongo docker installation I found this.

**Comment by birm** [comment]
Can please you tell me what the commit hash and file are for the compose file you're using?

**Comment by catweis** [comment]
I am using the latest from 2 months ago. Its hash is 4f107ac.

**Comment by birm** [comment]
Have you resolved/explained this issue?

I'm not sure why ca-back has complained about the "updateMarksLabel" as 3.10.0 _should_ have it -- https://github.com/camicroscope/Caracal/blob/v3.10.0/handlers/dataHandlers.js#L258

**Comment by birm** [comment]
Closing since we've had a release since, so I think this issue is stale. Please reopen if the problem persists.
