### ISSUE TITLE
docker-compose -f caMicroscope.yml up command failed to run

### ISSUE THREAD

**Issue by Ahmad-Bin-Zahid** [camicroscope/Distro#206]
I simply ran the docker commad docker-compose -f caMicroscope.yml up which failed with the folllowing error message. Can someone please help me on this.
![Screenshot 2023-05-17 at 4 18 35 PM](https://github.com/camicroscope/Distro/assets/99171841/3861ea21-44b1-4bfc-a0e0-fdce26952953)

**Comment by claudejin** [comment]
I have met the same problem with @Ahmad-Bin-Zahid. And tried what @birm said, anad it works.
![image](https://github.com/camicroscope/Distro/assets/5445455/10657219-a5e8-4438-ab39-b3114e92dad7)

**Comment by Ahmad-Bin-Zahid** [comment]
@birm yes the command you shared ran successfully
![Screenshot 2023-05-19 at 4 18 29 PM](https://github.com/camicroscope/Distro/assets/99171841/83a3fa35-704d-4493-8287-ac6f3c010023)

**Comment by Ahmad-Bin-Zahid** [comment]
I wanna deploy this somewhere for testing. How should I proceed considering the main command was not working?

**Comment by birm** [comment]
The docker base container of docker we used (stretch) is no longer supported. We just need to do a release in the near future.

In the meantime, depending on what you're testing, you might be able to use develop.yml; the main differences are that we're using pre-release code and have disabled most security features there.

**Comment by Ahmad-Bin-Zahid** [comment]
Well I kinda fixed the issue. I simply removed the existing container and again build the image. After that the command ran with no issues.

**Comment by birm** [comment]
I think the move away from depreciated ubuntu base images fixed this, please reopen if this issue persists.
