### ISSUE TITLE
ca-iip restarting and exitting in a loop, trying to change ownership

### ISSUE THREAD

**Issue by utselmeg** [camicroscope/Distro#208]
Based on #206, I'm using `docker-compose -f develop.yml build --no-cache loader` to build the containers. 

Expected behavior
The ca-iip restarting, exiting, and restarting, and exiting. The error message shown in the screenshot would come up each time.

Desktop
 - OS: Venture 13.4
 - Browser: Chrome
 - Version: Version 114.0.5735.106 (Official Build) (arm64)

<img width="594" alt="Screenshot 2023-06-12 at 18 06 36" src="https://github.com/camicroscope/Distro/assets/30243573/c337e5ce-2b14-4b90-bfb1-ecba5a6d82ac">

Additional
I also want to start contributing to camicroscope. based on the current caMicroscope.yml file being out of date, how should i go about starting my contributions using the develop.yml?

Thanks so much!

**Comment by birm** [comment]
@utselmeg, I'm closing this issue because I think it's fixed. Please reopen this if it persists on the develop branch.
