### ISSUE TITLE
Issue with file develop.yml

### ISSUE THREAD

**Issue by EslamAsHhraf** [camicroscope/Distro#217]
**Describe the bug**

**To Reproduce**
1. When run ```sudo docker-compose -f develop.yml build```
2. Give me the following error
```
Building dicomsrv
ERROR: error fetching: fatal: couldn't find remote ref master
: exit status 128
```

**Screenshots**
![image](https://github.com/camicroscope/Distro/assets/71986226/8bf9005b-7bda-4eb9-b02a-7d1f08584d9d)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by birm** [comment]
Interesting, I didn't have the same issue, but I'll merge #218
