### ISSUE TITLE
when i post 

### ISSUE THREAD

**Issue by shaokeke** [camicroscope/Distro#33]
![image](https://user-images.githubusercontent.com/37448773/56403855-ebf71b00-6295-11e9-9ad3-aee5dd09c68a.png)

**Comment by birm** [comment]
Thank you for reporting. Is this on your own deployment, or is this from camicroscope.org?

**Comment by shaokeke** [comment]
![image](https://user-images.githubusercontent.com/37448773/56449338-4f428500-634a-11e9-8aa1-2f9154df85a7.png)
![image](https://user-images.githubusercontent.com/37448773/56449340-55386600-634a-11e9-8b67-e0bdbb54cec1.png)
on my own deployment

**Comment by shaokeke** [comment]
thanks

**Comment by birm** [comment]
Oh, a mongo error! Can you please remove lines 9 and 10 of camicroscope.yml (```    logging:
driver: none``` under mongo) and run this again?

**Comment by birm** [comment]
usually this issue is due to either disk space issues, or more likely ./db being set up for a different version of mongo. If this is the case, you can clear that folder and/or remove the `./db:/data/db` volume from the mongo service (line 8 in caMicroscope.yml)
