### ISSUE TITLE
Information Dashboard (Data[base] Summaries)

### ISSUE THREAD

**Issue by birm** [camicroscope/Distro#95]
**Is your feature request related to a problem? Please describe.**
Frequently, users/administrators are interested in a summary of data in the database.

**Describe the solution you'd like**
A simple page that answers some questions about items, mostly at the slide level.
Questions such as - how many images have at least one annotation associated with them? one heatmap?
This may be able to be done in browser, but there's no issue with requesting/making more data endpoints if needed.

**Comment by Hemansh31** [comment]
@birm I would like to work on this issue. Could you give me some pointers as to where to start and maybe a pointer to some sample data so that I can reproduce the problem???

**Comment by birm** [comment]
We have a test seeder that generates essentially fake results -- https://github.com/camicroscope/Distro/blob/master/config/test_seed.js; you could use this to add some results to the database to look at if you like.

**Comment by Hemansh31** [comment]
@birm I am not able to run this file, could you please guide me on how to run this??

**Comment by birm** [comment]
run `docker exec -it ca-mongo mongo` to get to the mongo instance, then `use camic` to use the camic database, then you can run the contents of this file, or other mongo commands.

**Comment by Vedant1202** [comment]
@birm I would like to work on this. I just wanted to know if you want a static display table showing the information or a more user interactive one?

**Comment by birm** [comment]
I think it's not a bad idea to start with a static one. Maybe a search/filter/sort like the slide table?

**Comment by Vedant1202** [comment]
Alright I'll get working on this.

**Comment by Hemansh31** [comment]
@birm I have created a PR regarding an initial implementation of the information dashboard.
https://github.com/camicroscope/caMicroscope/pull/323
Please review and suggest any major changes you think are needed.
