### ISSUE TITLE
Simplify the Microservice Architecture

### ISSUE THREAD

**Issue by birm** [camicroscope/Distro#96]
**Is your feature request related to a problem? Please describe.**
caMicroscope needs, at the least, a good access control system. This is complicated by having _two_ middleware agents (bindaas and security). This would allow us to have a centralized caMicroscope setup. Then, as long as we keep everything stateless, we can scale on _microservice_ rather than _project_. 

**Describe the solution you'd like**
Late last year, caboodle (https://github.com/camicroscope/caboodle) was born. It's still a baby, so let's revisit it, test it thoroughly, make required changes to the ui, and release it.

I've assigned this to myself since it's kind of big and touches everything.

**Comment by NamanZelawat** [comment]
@birm I would like to help you with that as I have some backend knowledge with the express, MongoDB and would like to participate in GSoC this year. Also looking up for project three which is related to some server image processing.

**Comment by birm** [comment]
Thanks for your interest!
Take a look at expiremental.yml if you like, and github.com/camicroscope/caboodle the horribly-named replacement that I'm hoping to use. I want to do more testing, and decide how some features work, but you're welcome to take a look! It needs review/cleaning anyway.

**Comment by NamanZelawat** [comment]
@birm Thanks for your reply working on it.

**Comment by NamanZelawat** [comment]
@birm One part of the project is login signup right. I can contribute the code for login and signup and some basic frontend for that then we can go for further functionalities.

**Comment by NamanZelawat** [comment]
If you say I can make issues on adding different functionality in the project CABOODLE(really horribly named).
