### ISSUE TITLE
Questions towards using the container 

### ISSUE THREAD

**Issue by zengchu2** [camicroscope/Distro#98]
Hi all, I have some questions towards the Distro local usage. 
**Setup:**
I clone the Distro directory and run the container of Distro using command `docker-compose -f caMicroscope.yml up` as suggested and go to localhost:4010
**Questions:**
1.  When I try to post an Image, I select a sample image from my local disk, click **Finish Upload**, **Check** without seeing error messages. When I click **Post** and wait for a few seconds, there comes an error message as shown in screen shot. 
![post_error](https://user-images.githubusercontent.com/32441682/75839624-a35a2a80-5d9f-11ea-89eb-5edbf1789b4c.png)
    I checked the directory "Distro/images" and found the newly created sample2.svs file (Which is not there before I hit the post). 
    Not sure if these messages are expected when run the app locally.

2.  After posting the image file as described above, when I go to  "app/table.html", there is no image loaded  and here is the screen shot.  I think there might be something unexpcted happening in my case but I don't know why. 
![table](https://user-images.githubusercontent.com/32441682/75839830-20859f80-5da0-11ea-8564-1d8c651dd4de.png)

**Comment by birm** [comment]
This is certainly concerning. Can I ask a few questions?
Do you have the body that your browser sent to try to post?
Is there anything more to the body of the 500 error? (there may not be due to what I thought was an already-reported issue about the api gateway eating errors)
Where is the slide from?

Thank you for your patience and for reporting. Our slide loading is pretty confusing at best.

**Comment by zengchu2** [comment]
### Post Slide

- The slide is selected from 'Distro/images' (re [https://github.com/camicroscope/Distro/tree/master/images](url) )
- Here are some more detailed steps I performed 
![upload](https://user-images.githubusercontent.com/32441682/75844206-b246da00-5dab-11ea-84b6-c70afafd5c38.png)
![check](https://user-images.githubusercontent.com/32441682/75844210-b4a93400-5dab-11ea-9c85-ca3f6e33528b.png)
![post](https://user-images.githubusercontent.com/32441682/75844211-b5da6100-5dab-11ea-90d7-5def4d79ec11.png)


- Here is the details of post request **http://localhost:4010/data/Slide/post?**:
**Header**:
POST /data/Slide/post HTTP/1.1
Host: localhost:4010
Connection: keep-alive
Content-Length: 309
DNT: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Content-Type: application/json; charset=utf-8
Accept: */*
Origin: http://localhost:4010
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:4010/apps/loader/loader.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Cookie: UserID=1580419694593353; lastContentInjectionMode=jquery
**Payload**:
location: "/images/sample.svs"
mpp-x: "0.499"
mpp-y: "0.499"
height: "2967"
width: "2220"
vendor: "aperio"
level_count: 1
objective: 20
md5sum: "1ad6e35c9d17e4d85fb7e3143b328efe"
study: ""
specimen: ""
upload_date: "3/4/2020, 12:02:00 AM"
name: "sample2"
mpp: 0.499
mpp_x: 0.499
mpp_y: 0.499

- Here is the response for the post request above:
{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"ca-data","host":"ca-data","port":"9099","__statusCode":500}
### View Table
- Request **http://localhost:4010/data/Template/find** headers:
GET /data/Template/find HTTP/1.1
Host: localhost:4010
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
DNT: 1
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:4010/apps/table.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Cookie: UserID=1580419694593353; lastContentInjectionMode=jquery

- Request **http://localhost:4010/data/Slide/find?** headers:
GET /data/Slide/find HTTP/1.1
Host: localhost:4010
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
DNT: 1
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:4010/apps/table.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Cookie: UserID=1580419694593353; lastContentInjectionMode=jquery


Thanks for your patience.

**Comment by vikasgola** [comment]
This error is due to uploading file with a name which is already present in `/images/` folder. Changing file name removes this error.

I think this should have been handled in slideuploder server which should change name of file on  uploading it to server or do something similar to this.

**Comment by zengchu2** [comment]
Thanks @vikasgola, but how about the error of showing 'No Data'. According the doc, I should be fine just simply lanuching the app using command `docker-compose -f caMicroscope.yml up` right @birm ?

**Comment by birm** [comment]
Yes; I wonder what's wrong with ca-data. Can I get more diagonistic information; namely, if you replicate this, run `docker ps` in another terminal?

**Comment by vikasgola** [comment]
@zengchu2 are you using windows?

**Comment by zengchu2** [comment]
Yes, and I am using powershell to build docker container.

**Comment by zengchu2** [comment]
> Yes; I wonder what's wrong with ca-data. Can I get more diagonistic information; namely, if you replicate this, run `docker ps` in another terminal?

I did not setup docker stuff on the embedded system Ubuntu, I just get a 'Cannot connect to the daemon at tcp://localhost:2375. Is this docker daemon running?'

**Comment by vikasgola** [comment]
@zengchu2 I have not tested this on windows. However, I tried it on ubuntu 16.04 and it runs as expected.

**Comment by zengchu2** [comment]
Hi all, here is what I get under **Ubuntu 18.04 LTS**
`
zengchu2@DESKTOP-9AMNB8N:/mnt/h/gsoc/Distro$ docker-compose -f caMicroscope.yml up
ca-mongo is up-to-date
ca-load is up-to-date
ca-auth is up-to-date
ca-iip is up-to-date
ca-security is up-to-date
Starting ca-front ...
Starting ca-data  ... error
Starting ca-idx   ...

ERROR: for ca-data  Cannot start service bindaas: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/h/gsoc/Distro/config/bindaas.config.json\\\" to rootfs \\\"/var/lib/docker/overlay2/8facbc375c88c3319c5d906d6854d0d88faf50d3df056b52832d60443432ac7f/merged\\\" at \\\"/var/lib/docker/overlay2/8facbc375c88c3319c5d906d6854d0d88faf50d3df056b52832d6Starting ca-front ... error
: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for ca-front  Cannot start service viewer: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/h/gsoc/Distro/config/login.html\\\" to rootfs \\\"/var/lib/docker/overlay2/07a37e85341dae5c4e6f8ccfebb8cac45cea695424a93ea32d494a6c404cd178/merged\\\" at \\\"/var/lib/docker/overlay2/07a37e85341dae5c4e6f8ccfebb8cac45cea695424a93ea32d494a6c404cd178/merged/var/www/html/login.html\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path existsStarting ca-idx   ... done

ERROR: for viewer  Cannot start service viewer: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/h/gsoc/Distro/config/login.html\\\" to rootfs \\\"/var/lib/docker/overlay2/07a37e85341dae5c4e6f8ccfebb8cac45cea695424a93ea32d494a6c404cd178/merged\\\" at \\\"/var/lib/docker/overlay2/07a37e85341dae5c4e6f8ccfebb8cac45cea695424a93ea32d494a6c404cd178/merged/var/www/html/login.html\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for bindaas  Cannot start service bindaas: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/h/gsoc/Distro/config/bindaas.config.json\\\" to rootfs \\\"/var/lib/docker/overlay2/8facbc375c88c3319c5d906d6854d0d88faf50d3df056b52832d60443432ac7f/merged\\\" at \\\"/var/lib/docker/overlay2/8facbc375c88c3319c5d906d6854d0d88faf50d3df056b52832d60443432ac7f/merged/root/bindaas/bin/bindaas.config.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

**Comment by vikasgola** [comment]
@zengchu2 are you trying to run it on Windows 10 WSL?

**Comment by jlevy44** [comment]
I'm getting this error as well. Uploads are successful, but nothing showing up in the data table viewer

**Comment by birm** [comment]
If you're all getting the same error, please share your docker version and the body and return from the call triggered by the "post" button

**Comment by birm** [comment]
I think there are at least three different issues floating about here. 

If you're getting something about ca-data's mounts failing i.e. "Are you trying to mount a directory onto a file" please let me know more about your system (docker version, compose version, os, etc). I have a windows machine, but not one which supports docker, so I have to admit that that's undertested on windows (not that it _should_ matter, but windows is always a bit of a pain for compatibility; maybe we'll add appveyor or something.)

If you're not noticing the mounting issue, and are feeling especially inquisitive, either use the develop.yml config or remove the logging driver none for the ca-data (bindaas) container. Maybe something else is up with bindaas for one of these issues.

If you're getting an issue about a https handler not being found, then let's put that in a new issue. I think that's more of a docker issue than a camic issue, but we can still troubleshoot.

I'm hoping that #96 will resolve this, though I'm sure we'll have entirely new quirks as a result.

Thanks for your patience. Let's figure out what's up!

**Comment by cjchirag7** [comment]
@birm , I have created a separate issue for htpps handler not being found : #107 . 
Is there any other way to run the application locally, maybe without using docker ?

**Comment by birm** [comment]
I think this has been resolved since we no longer mount in files directly.
