### ISSUE TITLE
Menu Bar to navigate

### ISSUE THREAD

**Issue by Hemansh31** [camicroscope/Distro#99]
While using caMicroscope a lack of menu bar always bugs me. I feel if there were a navigation bar for all the sections of the web app it would be more user friendly.
**Possible Solution:**
adding a menu bar to facilitate easy navigation

@birm would you assign this issue to me?

**Comment by birm** [comment]
I'll be interested to see what you come up with, and I'll tag @nanli-emory who did most of our UI design.
